### ISSUE TITLE
not working with gnome-desktop3 3.22.2-2

### ISSUE THREAD

**Issue by Baefisch** [sciancio/connectionmanager2#65]
not able to use connection manager after updating to current centOS release. Before it works fine. 

Nov 28 15:24:05 lnx-rbg04 journal: JS WARNING: [resource:///org/gnome/shell/ui/extensionSystem.js 71]: reference to undefined property "connectionmanager@ciancio.net"
Nov 28 15:24:05 lnx-rbg04 org.gnome.Software: 14:24:05:0936 Gs  no app for changed connectionmanager2@ciancio.net
Nov 28 15:24:05 lnx-rbg04 journal: JS WARNING: [/home/fb/.local/share/gnome-shell/extensions/connectionmanager2@ciancio.net/extension.js 100]: Too many arguments to function GLib.file_get_contents: expected 1, got 3
Nov 28 15:24:05 lnx-rbg04 journal: Extension "connectionmanager2@ciancio.net" had error: TypeError: this.child.Name.quote is not a function

**Comment by sciancio** [comment]
Updated to Gnome Shell 3.32.
